/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nepal.auctionhouse.ui.lot.assign;

import com.nepal.auctionhouse.bll.lot.LotBLL;
import com.nepal.auctionhouse.bll.lot.LotStateBLL;
import com.nepal.auctionhouse.entity.Lot;
import com.nepal.auctionhouse.entity.LotMeta;
import com.nepal.auctionhouse.entity.LotState;
import com.nepal.auctionhouse.entity.Sale;
import com.nepal.auctionhouse.entity.user.UserInfo;
import com.nepal.auctionhouse.exception.RecordNotFoundException;
import com.nepal.auctionhouse.params.LotParams;
import com.nepal.auctionhouse.params.LotStateParams;
import com.nepal.auctionhouse.ui.BaseUserPanel;
import com.nepal.auctionhouse.util.Logy;
import com.nepal.auctionhouse.view.LotView;
import com.nepal.auctionhouse.widget.Alert;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suzn
 */
public final class LotAssignedPanel extends BaseUserPanel implements LotView<Lot> {

    private final UserInfo userInfo;

    /**
     * Creates new form LotAssignedPanel
     *
     * @param userInfo
     */
    public LotAssignedPanel(UserInfo userInfo) {
        initComponents();
        setupUserView(userInfo);
        this.userInfo = userInfo;
        Logy.d("Admin lotAssigned panel initialized");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        centerSubPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bidLotButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(249, 249, 249));
        searchPanel.setPreferredSize(new java.awt.Dimension(367, 70));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        searchPanel.setLayout(flowLayout1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 65));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_blue.png"))); // NOI18N

        searchTextField.setBackground(new java.awt.Color(249, 249, 249));
        searchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTextField.setToolTipText("Search for lot number,description,type..");
        searchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(39, 26, 252)));
        searchTextField.setMinimumSize(new java.awt.Dimension(200, 15));
        searchTextField.setOpaque(false);
        searchTextField.setPreferredSize(new java.awt.Dimension(200, 15));
        searchTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                System.out.println(text);
                if (text.trim().length() == 0) {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(javax.swing.RowFilter.regexFilter("^(?i)" + text));
                }
                table.repaint();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                if (text.trim().length() == 0) {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(javax.swing.RowFilter.regexFilter("^(?i)" + text));
                }
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                //not needed: throw new UnsupportedOperationException("Not supported yet.");
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        searchPanel.add(jPanel2);

        jPanel4.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        centerSubPanel.setLayout(new java.awt.CardLayout());

        DefaultTableModel tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        tableModel.addColumn(LotParams.LotAssignedTableHeader.ID);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.DESCRIPTION);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.TYPE);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.RESERVE_PRICE);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.AUCTION);
        table.setModel(tableModel);
        table.setRowHeight(26);
        table.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(table);
        javax.swing.table.TableRowSorter<javax.swing.table.TableModel> rowSorter = new javax.swing.table.TableRowSorter<>(table.getModel());
        table.setRowSorter(rowSorter);

        centerSubPanel.add(jScrollPane1, "card2");

        jPanel4.add(centerSubPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jPanel3.setOpaque(false);

        bidLotButton.setText("Bid");
        bidLotButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(255, 51, 0), new java.awt.Color(255, 51, 0)));
        bidLotButton.setPreferredSize(new java.awt.Dimension(80, 40));
        bidLotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidLotButtonActionPerformed(evt);
            }
        });
        jPanel3.add(bidLotButton);

        bottomPanel.add(jPanel3);

        jPanel4.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.add(jPanel4, "card2");

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bidLotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidLotButtonActionPerformed
        int row = table.getSelectedRow();
        if (row > -1) {
            try {
                LotMeta u = getBeanFromRow(table.getRowSorter().convertRowIndexToModel(row));
                if (u != null) {
                    LotBidDialog lotBidDialog = new LotBidDialog((JFrame) SwingUtilities.getWindowAncestor(this),
                            true, u, userInfo);
                    lotBidDialog.setItemUpdatedListener((Sale sale) -> {
                        updateLotAssignedData(sale);
                        loadTableData();
                    });
                    lotBidDialog.setVisible(true);
                }
            } catch (SQLException ex) {
                Logy.e(ex);
                Alert.showError(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_bidLotButtonActionPerformed

    @Override
    public final void loadTableData() {
        SwingUtilities.invokeLater(() -> {
            Logy.d("Loading lotAssigned from database");
            try {
                List<Lot> lotList = LotBLL.getAssignedLot();
                this.fillTableData(lotList);
            } catch (SQLException ex) {
                Logy.e(ex);
                Alert.showError(this, ex.getMessage());
            }

        });
    }

    @Override
    public final void fillTableData(List<Lot> list) {

        createTableModel();

        list.stream().forEach((lotAssigned) -> {
            onLotRowDataAdd(lotAssigned);
        });
    }

    @Override
    public void onLotRowDataAdd(Lot lotAssigned) {
        ((DefaultTableModel) table.getModel()).insertRow(0, new Object[]{
            lotAssigned.getId(),
            lotAssigned.getId(),
            lotAssigned.getDescription(),
            lotAssigned.getType().getTitle(),
            lotAssigned.getReservePrice(),
            lotAssigned.getAuction().getId()
        });
    }

    private void updateLotAssignedData(Sale sale) {
        try {
            LotState lotState = LotStateBLL.getLotStateById(LotStateParams.STATE_SOLD);
            sale.getLot().setState(lotState);
            LotBLL.updateLot(sale.getLot());
        } catch (RecordNotFoundException | SQLException ex) {
            Logy.e(ex);
            Alert.showError(this, ex.getMessage());
        }
    }

    @Override
    public void onLotDataRemove(Lot u) {

    }

    private LotMeta getBeanFromRow(int row) throws SQLException {
        int id = (int) table.getModel().getValueAt(row, 0);
        return LotBLL.getLotMetaByLotId(id);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bidLotButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerSubPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onViewActivated() {
        this.loadTableData();
    }

    @Override
    public void createTableModel() {
        DefaultTableModel tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        tableModel.addColumn(LotParams.LotAssignedTableHeader.ID);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.LOT_NUMBER);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.DESCRIPTION);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.TYPE);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.RESERVE_PRICE);
        tableModel.addColumn(LotParams.LotAssignedTableHeader.AUCTION);

        table.setModel(tableModel);
        javax.swing.table.TableRowSorter<javax.swing.table.TableModel> rowSorter = new javax.swing.table.TableRowSorter<>(table.getModel());
        table.setRowSorter(rowSorter);
    }

    @Override
    protected void setupAdminView() {
        bidLotButton.setVisible(false);
    }

    @Override
    protected void setupUserView() {
    }

}
