/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nepal.auctionhouse.ui.dashboard;

import com.nepal.auctionhouse.entity.user.UserInfo;
import com.nepal.auctionhouse.ui.auction.AuctionPanel;
import com.nepal.auctionhouse.ui.home.HomePanel;
import com.nepal.auctionhouse.ui.login.Login;
import com.nepal.auctionhouse.ui.lot.LotPanel;
import com.nepal.auctionhouse.ui.user.UserPanel;
import com.nepal.auctionhouse.util.ComponentUtils;
import com.nepal.auctionhouse.util.Logy;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Suzn
 */
public final class AdminDashboard extends BaseDashboard {

    private HomePanel homePanel;
    private AuctionPanel auctionPanel;
    private LotPanel lotPanel;
    private UserPanel userPanel;
    private final UserInfo userInfo;

    /**
     * Creates new form AdminDashboard
     *
     * @param userInfo
     */
    public AdminDashboard(UserInfo userInfo) {
        initComponents();
        setLocationRelativeTo(null);
        this.userInfo = userInfo;
        ComponentUtils.addToPanel(this.centerPanel, getHomePanel());
        Logy.d("Dashboard panel initialized");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rootPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        homeMenuButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        auctionMenuButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lotMenuButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        userMenuButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        saleMenuButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        profileMenuButton = new javax.swing.JButton();
        logoutButtonPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LBEF Auction House - Admin Panel");
        setExtendedState(6);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        setMinimumSize(new java.awt.Dimension(720, 630));
        getContentPane().setLayout(new java.awt.CardLayout());

        rootPanel.setBackground(new java.awt.Color(214, 217, 223));
        rootPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(39, 26, 252));
        topPanel.setLayout(new java.awt.GridLayout(1, 1, 10, 10));

        titlePanel.setBackground(new java.awt.Color(67, 160, 71));
        titlePanel.setPreferredSize(new java.awt.Dimension(508, 145));
        titlePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(185, 135));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(185, 135));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        titlePanel.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(39, 26, 252));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LBEF Auction House");

        jLabel4.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bid It To Win It");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        titlePanel.add(jPanel1);

        topPanel.add(titlePanel);

        rootPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setMinimumSize(new java.awt.Dimension(300, 10));
        centerPanel.setOpaque(false);
        centerPanel.setPreferredSize(new java.awt.Dimension(500, 10));
        centerPanel.setLayout(new java.awt.CardLayout());
        rootPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        leftPanel.setBackground(new java.awt.Color(214, 217, 223));
        leftPanel.setMinimumSize(new java.awt.Dimension(150, 10));
        leftPanel.setPreferredSize(new java.awt.Dimension(180, 412));
        leftPanel.setLayout(new java.awt.CardLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);

        jPanel8.setBackground(new java.awt.Color(249, 249, 249));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBackground(new java.awt.Color(153, 0, 153));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(136, 70));

        homeMenuButton.setBackground(new java.awt.Color(67, 160, 71));
        homeMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        homeMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeMenuButton.setText("Home");
        homeMenuButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(255, 0, 0)));
        buttonGroup1.add(homeMenuButton);
        homeMenuButton.setContentAreaFilled(false);
        homeMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeMenuButton.setIconTextGap(10);
        homeMenuButton.setOpaque(true);
        homeMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home1x.png"))); // NOI18N
        homeMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuButton.setBorder(selectedDashboardMenuBorder);
                auctionMenuButton.setBorder(defaultDashboardMenuBorder);
                lotMenuButton.setBorder(defaultDashboardMenuBorder);
                userMenuButton.setBorder(defaultDashboardMenuBorder);
                saleMenuButton.setBorder(defaultDashboardMenuBorder);
                profileMenuButton.setBorder(defaultDashboardMenuBorder);
                homeMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel5);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setOpaque(false);

        auctionMenuButton.setBackground(new java.awt.Color(67, 160, 71));
        auctionMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        auctionMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        auctionMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/auction.png"))); // NOI18N
        auctionMenuButton.setText("Auction");
        auctionMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buttonGroup1.add(auctionMenuButton);
        auctionMenuButton.setContentAreaFilled(false);
        auctionMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        auctionMenuButton.setIconTextGap(10);
        auctionMenuButton.setMargin(new java.awt.Insets(2, 15, 2, 14));
        auctionMenuButton.setOpaque(true);
        auctionMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/auction.png"))); // NOI18N
        auctionMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/auction1x.png"))); // NOI18N
        auctionMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auctionMenuButton.setBorder(selectedDashboardMenuBorder);
                homeMenuButton.setBorder(defaultDashboardMenuBorder);
                lotMenuButton.setBorder(defaultDashboardMenuBorder);
                userMenuButton.setBorder(defaultDashboardMenuBorder);
                saleMenuButton.setBorder(defaultDashboardMenuBorder);
                profileMenuButton.setBorder(defaultDashboardMenuBorder);
                auctionMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(auctionMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(auctionMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(136, 70));

        lotMenuButton.setBackground(new java.awt.Color(67, 160, 71));
        lotMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lotMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        lotMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lot.png"))); // NOI18N
        lotMenuButton.setText("Lot");
        lotMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buttonGroup1.add(lotMenuButton);
        lotMenuButton.setContentAreaFilled(false);
        lotMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lotMenuButton.setIconTextGap(10);
        lotMenuButton.setOpaque(true);
        lotMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lot.png"))); // NOI18N
        lotMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lot1x.png"))); // NOI18N
        lotMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotMenuButton.setBorder(selectedDashboardMenuBorder);
                auctionMenuButton.setBorder(defaultDashboardMenuBorder);
                homeMenuButton.setBorder(defaultDashboardMenuBorder);
                userMenuButton.setBorder(defaultDashboardMenuBorder);
                saleMenuButton.setBorder(defaultDashboardMenuBorder);
                profileMenuButton.setBorder(defaultDashboardMenuBorder);
                lotMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lotMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lotMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(136, 70));

        userMenuButton.setBackground(new java.awt.Color(67, 160, 71));
        userMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        userMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff.png"))); // NOI18N
        userMenuButton.setText("User");
        userMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buttonGroup1.add(userMenuButton);
        userMenuButton.setContentAreaFilled(false);
        userMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userMenuButton.setIconTextGap(10);
        userMenuButton.setOpaque(true);
        userMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff.png"))); // NOI18N
        userMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff1x.png"))); // NOI18N
        userMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMenuButton.setBorder(selectedDashboardMenuBorder);
                auctionMenuButton.setBorder(defaultDashboardMenuBorder);
                homeMenuButton.setBorder(defaultDashboardMenuBorder);
                lotMenuButton.setBorder(defaultDashboardMenuBorder);
                saleMenuButton.setBorder(defaultDashboardMenuBorder);
                profileMenuButton.setBorder(defaultDashboardMenuBorder);
                userMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(136, 70));

        saleMenuButton.setBackground(new java.awt.Color(67, 160, 71));
        saleMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saleMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        saleMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale.png"))); // NOI18N
        saleMenuButton.setText("Sale");
        saleMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buttonGroup1.add(saleMenuButton);
        saleMenuButton.setContentAreaFilled(false);
        saleMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saleMenuButton.setIconTextGap(10);
        saleMenuButton.setOpaque(true);
        saleMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale.png"))); // NOI18N
        saleMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale1x.png"))); // NOI18N
        saleMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleMenuButton.setBorder(selectedDashboardMenuBorder);
                homeMenuButton.setBorder(defaultDashboardMenuBorder);
                auctionMenuButton.setBorder(defaultDashboardMenuBorder);
                lotMenuButton.setBorder(defaultDashboardMenuBorder);
                userMenuButton.setBorder(defaultDashboardMenuBorder);
                profileMenuButton.setBorder(defaultDashboardMenuBorder);
                saleMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saleMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saleMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(136, 70));

        profileMenuButton.setBackground(new java.awt.Color(67, 160, 71));
        profileMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        profileMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        profileMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member.png"))); // NOI18N
        profileMenuButton.setText("Profile");
        profileMenuButton.setToolTipText("");
        profileMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        buttonGroup1.add(profileMenuButton);
        profileMenuButton.setContentAreaFilled(false);
        profileMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileMenuButton.setIconTextGap(10);
        profileMenuButton.setOpaque(true);
        profileMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member.png"))); // NOI18N
        profileMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member1x.png"))); // NOI18N
        profileMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileMenuButton.setBorder(selectedDashboardMenuBorder);
                homeMenuButton.setBorder(defaultDashboardMenuBorder);
                auctionMenuButton.setBorder(defaultDashboardMenuBorder);
                lotMenuButton.setBorder(defaultDashboardMenuBorder);
                userMenuButton.setBorder(defaultDashboardMenuBorder);
                saleMenuButton.setBorder(defaultDashboardMenuBorder);
                profileMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileMenuButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel11);

        logoutButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoutButtonPanel.setOpaque(false);

        logoutButton.setBackground(new java.awt.Color(255, 82, 36));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        logoutButton.setContentAreaFilled(false);
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutButton.setIconTextGap(10);
        logoutButton.setOpaque(true);
        logoutButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout1x.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logoutButtonPanelLayout = new javax.swing.GroupLayout(logoutButtonPanel);
        logoutButtonPanel.setLayout(logoutButtonPanelLayout);
        logoutButtonPanelLayout.setHorizontalGroup(
            logoutButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoutButtonPanelLayout.setVerticalGroup(
            logoutButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        leftPanel.add(jPanel6, "card2");

        rootPanel.add(leftPanel, java.awt.BorderLayout.LINE_START);

        getContentPane().add(rootPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Logy.d("Logout button clicked");
        Login login = new Login();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void homeMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Logy.d("Home menu clicked");
        ComponentUtils.addToPanel(this.centerPanel, getHomePanel());
    }

    private void auctionMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Logy.d("Auction menu clicked");
        ComponentUtils.addToPanel(this.centerPanel, getAuctionPanel());
    }

    private void profileMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Logy.d("Profile menu clicked");
//        ComponentUtils.addToPanel(this.centerPanel, getTransactionPanel());
    }

    private void lotMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Logy.d("Lot menu clicked");
        ComponentUtils.addToPanel(this.centerPanel, getLotPanel());
    }

    private void userMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Logy.d("User menu clicked");
        ComponentUtils.addToPanel(this.centerPanel, getUserPanel());
    }

    private void saleMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Logy.d("Sale menu clicked");
//        ComponentUtils.addToPanel(this.centerPanel, getReportPanel());
    }

    private AuctionPanel getAuctionPanel() {
        if (auctionPanel == null) {
            Logy.d("Creating auction panel instance");
            auctionPanel = new AuctionPanel(userInfo);
        }
        auctionPanel.onViewActivated();

        return auctionPanel;
    }

    private LotPanel getLotPanel() {
        if (lotPanel == null) {
            Logy.d("Creating lot panel instance");
            lotPanel = new LotPanel(userInfo);
        }
        lotPanel.onViewActivated();

        return lotPanel;
    }

    private UserPanel getUserPanel() {
        if (userPanel == null) {
            Logy.d("Creating user panel instance");
            userPanel = new UserPanel(userInfo);
        }
        userPanel.onViewActivated();
        return userPanel;
    }

    private HomePanel getHomePanel() {
        if (homePanel == null) {
            Logy.d("Creating home panel instance");
            homePanel = new HomePanel(userInfo);
        }
        return homePanel;
    }

//    private HomePanel getTransactionPanel() {
//        if (homePanel == null) {
//            Logy.d("Creating transaction panel instance");
//            homePanel = new HomePanel(userInfo);
//        }
//
//        return homePanel;
//    }
//
//    private ReportPanel getReportPanel() {
//        if (reportPanel == null) {
//            Logy.d("Creating report panel instance");
//            reportPanel = new ReportPanel(userInfo);
//        }
//
//        return reportPanel;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ignored) {
            Logy.e(ignored);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminDashboard(new UserInfo()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auctionMenuButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton homeMenuButton;
    private javax.swing.border.Border defaultDashboardMenuBorder = javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0);
    private javax.swing.border.Border selectedDashboardMenuBorder = javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(255, 0, 0));
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel logoutButtonPanel;
    private javax.swing.JButton lotMenuButton;
    private javax.swing.JButton profileMenuButton;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saleMenuButton;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton userMenuButton;
    // End of variables declaration//GEN-END:variables

}
